[package]
name = "flog-runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true

[[bin]]
name = "flogvm"
path = "src/main.rs"

[dependencies]
