[package]
name = "flog-compiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true

[[bin]]
name = "flogc"
path = "src/main.rs"

[dependencies]
error-stack = "0.3.1"
num-bigint = "0.4.3"

