[package]
name = "compiler"
version.workspace = true
authors.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true

[[bin]]
name = "flogc"
path = "src/main.rs"

[dependencies]
